CREATE TABLE IF NOT EXISTS `order` (
 `nodegroup` VARCHAR(255) NOT NULL,
 `_appsha` CHAR(64) NOT NULL,
 `app` VARCHAR(1024) NOT NULL,
 `order` INT(10) UNSIGNED NOT NULL DEFAULT 100,
 UNIQUE KEY (`_appsha`, `nodegroup`),
 CONSTRAINT FOREIGN KEY (`nodegroup`) REFERENCES nodegroups(`nodegroup`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `order_history` (
 `_appsha`  CHAR(64) NOT NULL,
 `app` VARCHAR(1024) NOT NULL,
 `nodegroup` VARCHAR(255) NOT NULL,
 `order` INT(10) UNSIGNED NOT NULL DEFAULT 100,
 `user` VARCHAR(255) NOT NULL,
 `timestamp` INT(10) UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
